version: '3.3'
services:
  nginx:
    container_name: nginx
    build: ./build/nginx
    volumes:
      - ./build/nginx/config:/etc/nginx/conf.d/
      - ./:/var/www
    ports:
      - ${EXTERNAL_PORT}:80
    links:
      - php
    restart: always
    tty: true
  php:
    container_name: php
    build: ./build/php
    volumes:
      - ./:/var/www
    links:
      - mysql
    restart: always
    tty: true
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./build/mysql/config/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./build/mysql/cache:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
    restart: always
    tty: true
